### PR TITLE
split name/dir, create theme_info function, relative paths, and change "bottstrap" to "bootlist"

### PR DESCRIPTION
**Pull request by mariez**
When phpList user merge this PR need to change the repository name to phplist-ui-bootlist, and need to update dev sites name directory. Otherwise nothing will work.

### CODE REVIEW

**Comment by michield** [comment]
Hmm, I'm not entirely happy with the way this has been implemented, but I will merge it and then update it. Have you written any docs on this yet? If not, wait with that until it's stabilised in a method of working.

**Comment by mariez** [comment]
No, I didn't wrote anything and didn't commited anything after this, waiting for you to see if this is ok. Any question im here. Any change you want me to do, ask me, or if you want me to implement this change in other way, just explain to me and I will do it. Happy new year!

**Comment by michield** [comment]
I have renamed this repo to match "bootlist" you may need to clone it again.

**Comment by michield** [comment]
You can now switch languages on http://dev.phplist.com/lists/admin/

Over to you. It will auto-update the Trevelin theme from this repository.

**Comment by mariez** [comment]
Cooooool! Trevelin! Bootlist is boried, i think our CEO is a too serious man, we need to take him to sailing or fly in paragliding :p
So what i should do different to you be "entirely happy"? You know i am an autodidact so it is very usefull for me to know this things so  i can learn for next time.

**Comment by mariez** [comment]
I have a question on this. I have a problem with this kind of switchers, and is that they don't record the choise, so every time you enter you have to choose your desire language or (now) desire theme.
Maybe we can associate the choise to each adminisitrator profile. as wordpress does. So we can remove this switchers from the sidebar and put them in the administrators profile page, for example:
http://dev.phplist.com/lists/admin/?page=admin&start=0&id=1
Then record the choise in a string for each administrator.
It is a very complicate change? Do you want me to add Sam to this conversation and see what he think?

**Comment by michield** [comment]
I agree with that. I made it for now to allow working on the theme, but I will add the selection to the admin profile page. In the long run we will control the theme with the config file only. Also, if there is only one theme available, the dropdown will not appear.

**Pull request merged**
